sudo: no

language: python

env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27-1.4
  - TOXENV=py27-1.7
  - TOXENV=py27-1.8
  - TOXENV=py27-1.9
  - TOXENV=py27-1.10
  - TOXENV=py27-1.11
  - TOXENV=py32-1.7
  - TOXENV=py32-1.8
  - TOXENV=py33-1.7
  - TOXENV=py33-1.8
  - TOXENV=py34-1.7
  - TOXENV=py34-1.8
  - TOXENV=py34-1.9
  - TOXENV=py34-1.10
  - TOXENV=py34-1.11
  - TOXENV=py34-master

matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py27-1.11
    - env: TOXENV=py34-1.11
    - env: TOXENV=py34-master

install:
  - pip install tox coveralls "virtualenv<14.0"

script:
  - tox

after_success:
  - coveralls
